spring.application.name=pedidos360-backend

# Puerto usado al desplegar en EC2 (paso 4.4 de la guia). Cambia a 8080 para pruebas 100% locales si se prefiere.
server.port=8888

# Issuer de tu User Pool de Cognito (usado por Spring Security para validar la firma, expiracion e issuer del JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_opOG7hsM7

